// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'childrenContainer': string;
  'contentHolder': string;
  'cross': string;
  'header': string;
  'modal': string;
  'modalContainer': string;
  'visible': string;
}
export const cssExports: CssExports;
export default cssExports;
