// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'fild': string;
  'fildHolder': string;
  'warning': string;
}
export const cssExports: CssExports;
export default cssExports;
